en:
  welcome: "Hello! I'm a bot for creating notes. Use /help for help and /note to create notes."
  note_created: "Note successfully created: %s"
  no_notes: "You don't have any notes yet."
  notes_list: "Your notes:\n"
  unknown_command: "Unknown command. Use /help for help and /note to create notes."
  note_creation_error: "An error occurred while creating the note."
  note_retrieval_error: "An error occurred while retrieving your notes."
  invalid_note_id: "Invalid note ID. Please provide a valid numeric ID."
  note_not_found: "Note not found or you don't have permission to delete it."
  note_deleted: "Note with ID %d successfully deleted."
  action_canceled: "Action canceled."
  unknown_action: "Unknown action. Please use the buttons provided."
  add_note_prompt: "Please send your note in the format: /note <text>"
  delete_note_prompt: "Select a note to delete:"
  enter_note_text: "Please enter the note text:"
  help_message: "Hello! I'm a bot for creating notes. Available commands:\n/start - Start the bot\n/help - Get help\n/notes - View your notes\n/settings - Change settings\n/delete_all_notes - Delete all your notes"


ru:
  welcome: "Привет! Я бот для создания заметок. Используй /help для спарвки и /note для создания заметок."
  note_created: "Заметка успешно создана: %s"
  no_notes: "У вас пока нет заметок."
  notes_list: "Ваши заметки:\n"
  unknown_command: "Неизвестная команда. Используй /help для спарвки и /note для создания заметок."
  note_creation_error: "Произошла ошибка при создании заметки."
  note_retrieval_error: "Произошла ошибка при получении ваших заметок."
  invalid_note_id: "Неверный ID заметки. Пожалуйста, укажите корректное числовое значение."
  note_not_found: "Заметка не найдена или у вас нет прав на её удаление."
  note_deleted: "Заметка с ID %d успешно удалена."
  action_canceled: "Действие отменено."
  unknown_action: "Неизвестное действие. Пожалуйста, используйте предоставленные кнопки."
  add_note_prompt: "Пожалуйста, отправьте заметку в формате: /note <текст>"
  delete_note_prompt: "Выберите заметку для удаления:"
  enter_note_text: "Пожалуйста, введите текст заметки:"
  help_message: "Привет! Я бот для создания заметок. Доступные команды:\n/start - Запустить бота\n/help - Получить помощь\n/notes - Посмотреть ваши заметки\n/settings - Изменить настройки\n/delete_all_notes - Удалить все ваши заметки"